---
 - name: Install openvpn proxy & collectd
   hosts: ipaopenvpn1
   become: false
   vars:
    ansible_ssh_pipelining: no
   vars_files:
    - ~/security/ipa/files/awsindia0cred.yml
    - ~/security/ipa/files/tf_variables
   tasks:
    - name: Disable require tty access in /etc/sudoers
      replace: dest="/etc/sudoers"
               regexp='^Defaults    requiretty'
               replace='Defaults    !requiretty'
      become: true
    - name: Set locale
      shell: export LC_ALL="en_US.UTF-8"
    - name: install openvpn pacakge
      command: apt-get install openvpn -y
      become: true
      ignore_errors: True
    - name: Create a new OpenVPN key
      shell: sudo openvpn --genkey --secret /etc/openvpn/ovpn.key
      ignore_errors: True
    - name: Create a new openvpn conf file
      file: path=/etc/openvpn/oregon-to-nv.conf state=touch
      become: true
      ignore_errors: True
    - name: Update openvpn conf file
      action: lineinfile
              dest="/etc/openvpn/oregon-to-nv.conf"
              line="port 1194\ndev tun\nstatus-version 2\nstatus openvpn-status.log\nlog openvpn-oregon.log\nlog-append  openvpn-oregon.log\nverb 6\n# Remote peer and network\nremote {{remote_openvpn_eip}}\nroute {{remote_vpc_network}} 255.255.255.0\n# Configure local and remote VPN endpoints\nifconfig {{ipa_openvpn_proxy_1_private_ip}} {{remote_openvpn_private_ip}}\n# The pre-shared static key\nsecret ovpn.key"
      become: true
    - name: Install apache
      command: "{{ item }}"
      with_items:
       - "apt-get update -y"
       - "apt-get install apache2 -y"
       - "a2enmod ssl"
      become: true
      ignore_errors: True
    - name: Creates directory
      file: path=/etc/apache2/ssl state=directory
      become: true
    - name: Create s self-signed SSL cert for apache
      shell: openssl req -x509 -nodes -subj "/C=US/ST=CA/L=Milpitas/O=Ops/CN=localhost" -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt
      become: true
    - name: Restart apache
      command: sudo service apache2 restart
      become: true
    - name: Install HTTP reverse proxy
      command: "{{ item }}"
      with_items:
       - "aptitude update -y"
       - "aptitude -y upgrade"
       - "aptitude install -y build-essential"
      become: true
    - name: Install Reverse Proxy dependencies
      command: aptitude install -y libapache2-mod-proxy-html libxml2-dev
      become: true
    - name: Activate modules
      command: "{{ item }}"
      with_items:
       - "a2enmod proxy"
       - "a2enmod proxy_http"
       - "a2enmod proxy_ajp"
       - "a2enmod rewrite"
       - "a2enmod deflate"
       - "a2enmod headers"
       - "a2enmod proxy_balancer"
       - "a2enmod proxy_connect"
       - "a2enmod proxy_html"
       - "a2enmod xml2enc"
      become: true
